# Generated by Django 4.0.4 on 2022-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_created_by'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='collection',
            field=models.ManyToManyField(default=None, related_name='owned_card', to='cards.card'),
        ),
    ]
