# Generated by Django 4.0.4 on 2022-04-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('strength', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('special', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
