# Generated by Django 4.0.4 on 2022-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
